<Project Sdk="RaptorRush135.PvZR.Sdk">

  <PropertyGroup>
    <IsModBuild>true</IsModBuild>
    <ModMelonType>$(RootNamespace).Core</ModMelonType>
    <ModColor>255, 0, 200, 0</ModColor>
  </PropertyGroup>

  <ItemGroup>
    <ModZipInclude Include="../../../README.md">
      <ZipPath>Docs/PvZRepatched-README.md</ZipPath>
    </ModZipInclude>
    <ModZipInclude Include="../../../LICENSE">
      <ZipPath>Docs/PvZRepatched-License.txt</ZipPath>
    </ModZipInclude>
    <ModZipInclude Include="Attributions/*.txt">
      <ZipPath>Docs/%(Filename)%(Extension)</ZipPath>
    </ModZipInclude>
  </ItemGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerDefaultPreReleaseIdentifiers>dev</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>

  <Target Name="EnableZipVersionDotReplacementForStableRelease" AfterTargets="MinVer" Condition="'$(MinVerPreRelease)' == ''">
    <PropertyGroup>
      <ModZipReplaceVersionDots>true</ModZipReplaceVersionDots>
    </PropertyGroup>
  </Target>

</Project>
